apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
  labels:
{{ include "azuredisk.labels" . | indent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
