include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.20
  script:
    # unset those to prevent loading incluster config during CI
    - export KUBERNETES_SERVICE_HOST=""
    - export KUBERNETES_SERVICE_PORT=""
    - go test ./pkg/... -v

build-docker-image:
  extends: .build-docker-image
