include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.20
  variables:
    # unset those to prevent loading incluster config during CI
    KUBERNETES_SERVICE_HOST: ""
    KUBERNETES_SERVICE_PORT: ""
  script:
    - go test ./pkg/... -v

build-docker-image:
  extends: .build-docker-image
