---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-azuredisk-controller
  namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: csi-azuredisk-controller
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          memory: 10Gi
        controlledResources: ["memory"]
