apiVersion: v1
entries:
  azuredisk-csi-driver:
  - apiVersion: v1
    appVersion: v2.0.0-alpha.1
    created: "2021-08-20T22:21:10.3320722Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b58fa509d0a96d112dd2718bdc4cd566b9c36f5ef24e99c9098bf064e8d3ff01
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
    version: v2.0.0-alpha.1
  - apiVersion: v1
    appVersion: latest
    created: "2021-08-20T22:21:10.2958896Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: f36203eb5aa905765ffbbfe879f32bef2efc8f7f2a2616018b286255f6c3a97b
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/latest/azuredisk-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.1
    created: "2021-08-20T22:21:10.3243071Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: efb42e1d56cc5596eb4e695b658c2748bc05cc6c47862e3f20ea6b5b199d01d6
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.5.1/azuredisk-csi-driver-v1.5.1.tgz
    version: v1.5.1
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2021-08-20T22:21:10.3231442Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: c8490efde8d4a43bd25f5c619887498dfb4b41edf3929ac8dbf0a9d3f691e6ae
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.5.0/azuredisk-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: latest
    created: "2021-08-20T22:21:10.2941948Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 7682eaf64255671c05b1fc034d591a27278e55c6674e2ed769d41668dee9097a
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/latest/azuredisk-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2021-08-20T22:21:10.3218173Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 55e5e17aac7c144b21a198867654ef70ad272987b0bb165782905adf91ca3c03
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.4.0/azuredisk-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2021-08-20T22:21:10.3206071Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2665483e922a577feb8539ca7f774bc70c945ce490294fd3378f098c2d244dde
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.3.0/azuredisk-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2021-08-20T22:21:10.3196458Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2bbfe2f9d080f1b3ff10590c7168d05ce026c5a73332b4d48014610a52337808
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.2.0/azuredisk-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.1
    created: "2021-08-20T22:21:10.3186982Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: dd7066be8f499f6c1a396ab27c0013c09f5a8d8319cc04fbdd480d31107bb851
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.1.1/azuredisk-csi-driver-v1.1.1.tgz
    version: v1.1.1
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2021-08-20T22:21:10.3178091Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3d2a5189416dd6a43bd3e2097bbe23a8db347b6e1a36c6a43fd59cc9c9633ff3
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.1.0/azuredisk-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2021-08-20T22:21:10.3091865Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: d179bc6f338518859b6efdc3b3bed8d06513313e8047563eb4b654b2d417c81e
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.0.0/azuredisk-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2021-08-20T22:21:10.2970935Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3dbbaca098fe8316de079236598253b5831e8e85fd88b390231d828157d62206
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.10.0/azuredisk-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2021-08-20T22:21:10.3082893Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: a978f3e6ef5d678c3b6512bd8a63277cb4ce40d3f3e34b80370f0c37298824f2
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.9.0/azuredisk-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: v0.8.0
    created: "2021-08-20T22:21:10.3021785Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 1762b832389b4f7a5eab9748127fa6dbb85131485d67bc3fe485bbe86c468128
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.8.0/azuredisk-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2021-08-20T22:21:10.300669Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 29e21f686814f46c1edaaaa95ce2d25579ff1aad270c58b774bdb5a89858b8bf
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.7.0/azuredisk-csi-driver-v0.7.0.tgz
    version: v0.7.0
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2021-08-20T22:21:10.2983682Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b11d8dfee371ca7c63a1448ba27c1fd1f032ea33575fefeeb16927fc95d1eeb7
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.6.0/azuredisk-csi-driver-v0.6.0.tgz
    version: v0.6.0
generated: "2021-08-20T22:21:10.2922706Z"
