name: Run integration test
on:
    pull_request: {}
jobs:
  test:
    name: Run integration test
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ secrets.TenantId }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.SubscriptionId }}
      AZURE_CLIENT_ID: ${{ secrets.ClientId }}
      AZURE_CLIENT_SECRET: ${{ secrets.ClientSecret }}
      AZURE_LOCATION: ${{ secrets.Location }}
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install conntrack
      run: sudo apt install conntrack

    - name: Integration Test
      run: |
        BUILD_V2=1 make integration-test-v2