name: Run integration test
on:
    pull_request: {}
    schedule:
    - cron: "0 13 * * *"
jobs:
  test:
    name: Run integration test
    runs-on: ubuntu-latest
    env:
      AZURE_TENANT_ID: ${{ secrets.TenantId }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.SubscriptionId }}
      AZURE_CLIENT_ID: ${{ secrets.ClientId }}
      AZURE_CLIENT_SECRET: ${{ secrets.ClientSecret }}
      AZURE_LOCATION: ${{ secrets.IntLocation }}
    
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install conntrack
      run: sudo apt install conntrack

    - name: Integration Test
      run: |
        BUILD_V2=true make integration-test-v2